export const FILTER_BY_NAME = "FILTER/BY_NAME";

export const SEARCH_BY_NAME_STARTED = "FILTER/SEARCH_BY_NAME_STARTED";
export const SEARCH_BY_NAME_SUCCESSED = "FILTER/SEARCH_BY_NAME_SUCCESSED";
export const SEARCH_BY_NAME_FAILURE = "FILTER/SEARCH_BY_NAME_FAILURE";
