export const FETCH_CONTACT_STARTED = "CONTACT/FETCH_STARTED";
export const FETCH_CONTACT_SUCCESS = "CONTACT/FETCH_SUCCESS";
export const FETCH_CONTACT_FAILURE = "CONTACT?FETCH_FAILURE";

export const TRIGGER_FAVORITE_CONTACT = "CONTACT/TRIGGER_FAVORITE";
export const REMOVE_CONTACT = "CONTACT/REMOVE";
